version: '3.8'

services:
  web:
    build: .
    ports:
      - "4999:5000" # can't use 5000, AirPlay uses it lol.
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
