# fly.toml app configuration file generated for channelify-gpt on 2023-11-26T18:31:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "channelify-gpt"
primary_region = "waw"

[env]
WHEN_PROCESS_CHANNELS="20:00:00"
PORT=5000

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
