name: Deploy GPT app
on:
  push:
    branches:
      - main
    paths:
      - gpt/**
      - .github/workflows/gpt.yml
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd gpt && flyctl deploy --remote-only -c fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_GPT }}
